server:
  port: 10003

spring:
  application:
    name: gateway
  cloud:
    # 配置网关
    gateway:
      #配置路由
      routes:
        - id: order_route #路由键，唯一值
          uri: lb://order-nacos # 使用服务名来转发
          # 断言规则
          predicates:
            - Path=/order-server/** #配置匹配的路径

          filters:
            - StripPrefix=1 #删除第一层路径
    #集成nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos

