server:
  port: 8001

spring:
  application:
    name: order-simple
  cloud:
    nacos:
      # 注册中心地址
      server-addr: localhost:8848

      #服务注册配置
      discovery:
        #配置nacos用户名和密码
        username: nacos
        password: nacos
        namespace: public
