server:
  port: 10000

spring:
  application:
    name: gateway
  cloud:
    # 配置网关
    gateway:
      #配置路由
      routes:
        - id: order_route #路由键，唯一值
          uri: http://localhost:8001 # 转发的路径
          # 断言规则
          predicates:
            - Path=/order-server/** #配置匹配的路径

          filters:
            - StripPrefix=1 #删除第一层路径
